root: true

globals:
  Webcom: true
  SDK_VERSION: true
  SCHEMA_VERSION: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  strict: 0
  indent:
    - 2
    - tab
    - SwitchCase: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  no-console:
    - 0
  complexity:
    - 2
    - 10
  max-depth:
    - 2
    - 3
  max-len:
    - 2
    - 120
    - 4
    - ignoreComments: true
  max-params:
    - 2
    - 4
  max-statements:
    - 2
    - 20
  require-jsdoc:
    - 2
  no-var:
    - 2
  object-shorthand:
    - 2
    - "always"
  prefer-arrow-callback:
    - 2
  prefer-const:
    - 2
  prefer-spread:
    - 2
  prefer-template:
    - 2
  no-use-before-define:
    - 2
  block-scoped-var:
    - 2
  curly:
    - 2
  eqeqeq:
    - 2
    - "smart"
  no-alert:
    - 2
  no-else-return:
    - 2
  no-labels:
    - 2
  no-lone-blocks:
    - 2
  no-loop-func:
    - 2
  no-new-wrappers:
    - 2
  no-param-reassign:
    - 2
  no-proto:
    - 2
  no-return-assign:
    - 2
  no-sequences:
    - 2
  no-throw-literal:
    - 2
  no-useless-call:
    - 2
  no-useless-concat:
    - 2
  no-with:
    - 2
  radix:
    - 2
env:
  es6: true
  browser: true
  node: true
  jasmine: true

extends: 'eslint:recommended'
