window.esdocSearchIndex = [
  [
    "webcom-reach/src/core/config.js~config",
    "class/src/core/Config.js~Config.html",
    "<span>Config</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Config.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/invite.js~invite",
    "class/src/core/Invite.js~Invite.html",
    "<span>Invite</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Invite.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/stream/local.js~local",
    "class/src/core/stream/Local.js~Local.html",
    "<span>Local</span> <span class=\"search-result-import-path\">webcom-reach/src/core/stream/Local.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/util/media.js~media",
    "class/src/core/util/Media.js~Media.html",
    "<span>Media</span> <span class=\"search-result-import-path\">webcom-reach/src/core/util/Media.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/message.js~message",
    "class/src/core/Message.js~Message.html",
    "<span>Message</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Message.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/participant.js~participant",
    "class/src/core/Participant.js~Participant.html",
    "<span>Participant</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Participant.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/webrtc/peerconnection.js~peerconnection",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html",
    "<span>PeerConnection</span> <span class=\"search-result-import-path\">webcom-reach/src/core/webrtc/PeerConnection.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/reach.js~reach",
    "class/src/Reach.js~Reach.html",
    "<span>Reach</span> <span class=\"search-result-import-path\">webcom-reach/src/Reach.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/stream/remote.js~remote",
    "class/src/core/stream/Remote.js~Remote.html",
    "<span>Remote</span> <span class=\"search-result-import-path\">webcom-reach/src/core/stream/Remote.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/room.js~room",
    "class/src/core/Room.js~Room.html",
    "<span>Room</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Room.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/user.js~user",
    "class/src/core/User.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">webcom-reach/src/core/User.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/reach.js",
    "file/src/Reach.js.html",
    "src/Reach.js",
    "file"
  ],
  [
    "src/reach.js~reach#anonymous",
    "class/src/Reach.js~Reach.html#instance-method-anonymous",
    "src/Reach.js~Reach#anonymous",
    "method"
  ],
  [
    "src/reach.js~reach#base",
    "class/src/Reach.js~Reach.html#instance-get-base",
    "src/Reach.js~Reach#base",
    "member"
  ],
  [
    "src/reach.js~reach#config",
    "class/src/Reach.js~Reach.html#instance-get-config",
    "src/Reach.js~Reach#config",
    "member"
  ],
  [
    "src/reach.js~reach#constructor",
    "class/src/Reach.js~Reach.html#instance-constructor-constructor",
    "src/Reach.js~Reach#constructor",
    "method"
  ],
  [
    "src/reach.js~reach#createroom",
    "class/src/Reach.js~Reach.html#instance-method-createRoom",
    "src/Reach.js~Reach#createRoom",
    "method"
  ],
  [
    "src/reach.js~reach#current",
    "class/src/Reach.js~Reach.html#instance-get-current",
    "src/Reach.js~Reach#current",
    "member"
  ],
  [
    "src/reach.js~reach#getroom",
    "class/src/Reach.js~Reach.html#instance-method-getRoom",
    "src/Reach.js~Reach#getRoom",
    "method"
  ],
  [
    "src/reach.js~reach#getuser",
    "class/src/Reach.js~Reach.html#instance-method-getUser",
    "src/Reach.js~Reach#getUser",
    "method"
  ],
  [
    "src/reach.js~reach#invites",
    "class/src/Reach.js~Reach.html#instance-method-invites",
    "src/Reach.js~Reach#invites",
    "method"
  ],
  [
    "src/reach.js~reach#login",
    "class/src/Reach.js~Reach.html#instance-method-login",
    "src/Reach.js~Reach#login",
    "method"
  ],
  [
    "src/reach.js~reach#logout",
    "class/src/Reach.js~Reach.html#instance-method-logout",
    "src/Reach.js~Reach#logout",
    "method"
  ],
  [
    "src/reach.js~reach#on",
    "class/src/Reach.js~Reach.html#instance-method-on",
    "src/Reach.js~Reach#on",
    "method"
  ],
  [
    "src/reach.js~reach#peerconnections",
    "class/src/Reach.js~Reach.html#instance-get-peerConnections",
    "src/Reach.js~Reach#peerConnections",
    "member"
  ],
  [
    "src/reach.js~reach#register",
    "class/src/Reach.js~Reach.html#instance-method-register",
    "src/Reach.js~Reach#register",
    "method"
  ],
  [
    "src/reach.js~reach#resume",
    "class/src/Reach.js~Reach.html#instance-method-resume",
    "src/Reach.js~Reach#resume",
    "method"
  ],
  [
    "src/reach.js~reach.audiobitratemax",
    "class/src/Reach.js~Reach.html#static-get-audioBitrateMax",
    "src/Reach.js~Reach.audioBitrateMax",
    "member"
  ],
  [
    "src/reach.js~reach.browser",
    "class/src/Reach.js~Reach.html#static-get-browser",
    "src/Reach.js~Reach.browser",
    "member"
  ],
  [
    "src/reach.js~reach.codecs",
    "class/src/Reach.js~Reach.html#static-get-codecs",
    "src/Reach.js~Reach.codecs",
    "member"
  ],
  [
    "src/reach.js~reach.communicationquality",
    "class/src/Reach.js~Reach.html#static-get-communicationQuality",
    "src/Reach.js~Reach.communicationQuality",
    "member"
  ],
  [
    "src/reach.js~reach.events",
    "class/src/Reach.js~Reach.html#static-get-events",
    "src/Reach.js~Reach.events",
    "member"
  ],
  [
    "src/reach.js~reach.media",
    "class/src/Reach.js~Reach.html#static-get-media",
    "src/Reach.js~Reach.media",
    "member"
  ],
  [
    "src/reach.js~reach.types",
    "class/src/Reach.js~Reach.html#static-get-types",
    "src/Reach.js~Reach.types",
    "member"
  ],
  [
    "src/reach.js~reach.version",
    "class/src/Reach.js~Reach.html#static-get-version",
    "src/Reach.js~Reach.version",
    "member"
  ],
  [
    "src/reach.js~reach.videobitratemax",
    "class/src/Reach.js~Reach.html#static-get-videoBitrateMax",
    "src/Reach.js~Reach.videoBitrateMax",
    "member"
  ],
  [
    "src/core/config.js",
    "file/src/core/Config.js.html",
    "src/core/Config.js",
    "file"
  ],
  [
    "src/core/config.js~config#[key]",
    "class/src/core/Config.js~Config.html#instance-member-[key]",
    "src/core/Config.js~Config#[key]",
    "member"
  ],
  [
    "src/core/config.js~config#audiobitratemax",
    "class/src/core/Config.js~Config.html#instance-member-audioBitrateMax",
    "src/core/Config.js~Config#audioBitrateMax",
    "member"
  ],
  [
    "src/core/config.js~config#communicationquality",
    "class/src/core/Config.js~Config.html#instance-member-communicationQuality",
    "src/core/Config.js~Config#communicationQuality",
    "member"
  ],
  [
    "src/core/config.js~config#constraints",
    "class/src/core/Config.js~Config.html#instance-member-constraints",
    "src/core/Config.js~Config#constraints",
    "member"
  ],
  [
    "src/core/config.js~config#iceservers",
    "class/src/core/Config.js~Config.html#instance-set-iceServers",
    "src/core/Config.js~Config#iceServers",
    "member"
  ],
  [
    "src/core/config.js~config#iceservers",
    "class/src/core/Config.js~Config.html#instance-get-iceServers",
    "src/core/Config.js~Config#iceServers",
    "member"
  ],
  [
    "src/core/config.js~config#localstreamcontainer",
    "class/src/core/Config.js~Config.html#instance-member-localStreamContainer",
    "src/core/Config.js~Config#localStreamContainer",
    "member"
  ],
  [
    "src/core/config.js~config#loglevel",
    "class/src/core/Config.js~Config.html#instance-set-logLevel",
    "src/core/Config.js~Config#logLevel",
    "member"
  ],
  [
    "src/core/config.js~config#loglevel",
    "class/src/core/Config.js~Config.html#instance-get-logLevel",
    "src/core/Config.js~Config#logLevel",
    "member"
  ],
  [
    "src/core/config.js~config#preferredaudiocodec",
    "class/src/core/Config.js~Config.html#instance-member-preferredAudioCodec",
    "src/core/Config.js~Config#preferredAudioCodec",
    "member"
  ],
  [
    "src/core/config.js~config#preferredvideocodec",
    "class/src/core/Config.js~Config.html#instance-member-preferredVideoCodec",
    "src/core/Config.js~Config#preferredVideoCodec",
    "member"
  ],
  [
    "src/core/config.js~config#remotestreamcontainer",
    "class/src/core/Config.js~Config.html#instance-member-remoteStreamContainer",
    "src/core/Config.js~Config#remoteStreamContainer",
    "member"
  ],
  [
    "src/core/config.js~config#stats",
    "class/src/core/Config.js~Config.html#instance-get-stats",
    "src/core/Config.js~Config#stats",
    "member"
  ],
  [
    "src/core/config.js~config#stats",
    "class/src/core/Config.js~Config.html#instance-set-stats",
    "src/core/Config.js~Config#stats",
    "member"
  ],
  [
    "src/core/config.js~config#videobitratemax",
    "class/src/core/Config.js~Config.html#instance-member-videoBitrateMax",
    "src/core/Config.js~Config#videoBitrateMax",
    "member"
  ],
  [
    "src/core/device.js",
    "file/src/core/Device.js.html",
    "src/core/Device.js",
    "file"
  ],
  [
    "src/core/invite.js",
    "file/src/core/Invite.js.html",
    "src/core/Invite.js",
    "file"
  ],
  [
    "src/core/invite.js~invite#accept",
    "class/src/core/Invite.js~Invite.html#instance-method-accept",
    "src/core/Invite.js~Invite#accept",
    "method"
  ],
  [
    "src/core/invite.js~invite#cancel",
    "class/src/core/Invite.js~Invite.html#instance-method-cancel",
    "src/core/Invite.js~Invite#cancel",
    "method"
  ],
  [
    "src/core/invite.js~invite#from",
    "class/src/core/Invite.js~Invite.html#instance-member-from",
    "src/core/Invite.js~Invite#from",
    "member"
  ],
  [
    "src/core/invite.js~invite#isaccepted",
    "class/src/core/Invite.js~Invite.html#instance-get-isAccepted",
    "src/core/Invite.js~Invite#isAccepted",
    "member"
  ],
  [
    "src/core/invite.js~invite#iscanceled",
    "class/src/core/Invite.js~Invite.html#instance-get-isCanceled",
    "src/core/Invite.js~Invite#isCanceled",
    "member"
  ],
  [
    "src/core/invite.js~invite#isongoing",
    "class/src/core/Invite.js~Invite.html#instance-get-isOnGoing",
    "src/core/Invite.js~Invite#isOnGoing",
    "member"
  ],
  [
    "src/core/invite.js~invite#isrejected",
    "class/src/core/Invite.js~Invite.html#instance-get-isRejected",
    "src/core/Invite.js~Invite#isRejected",
    "member"
  ],
  [
    "src/core/invite.js~invite#off",
    "class/src/core/Invite.js~Invite.html#instance-method-off",
    "src/core/Invite.js~Invite#off",
    "method"
  ],
  [
    "src/core/invite.js~invite#offstatuschange",
    "class/src/core/Invite.js~Invite.html#instance-method-offStatusChange",
    "src/core/Invite.js~Invite#offStatusChange",
    "method"
  ],
  [
    "src/core/invite.js~invite#on",
    "class/src/core/Invite.js~Invite.html#instance-method-on",
    "src/core/Invite.js~Invite#on",
    "method"
  ],
  [
    "src/core/invite.js~invite#onstatuschange",
    "class/src/core/Invite.js~Invite.html#instance-method-onStatusChange",
    "src/core/Invite.js~Invite#onStatusChange",
    "method"
  ],
  [
    "src/core/invite.js~invite#reject",
    "class/src/core/Invite.js~Invite.html#instance-method-reject",
    "src/core/Invite.js~Invite#reject",
    "method"
  ],
  [
    "src/core/invite.js~invite#room",
    "class/src/core/Invite.js~Invite.html#instance-member-room",
    "src/core/Invite.js~Invite#room",
    "member"
  ],
  [
    "src/core/invite.js~invite#status",
    "class/src/core/Invite.js~Invite.html#instance-member-status",
    "src/core/Invite.js~Invite#status",
    "member"
  ],
  [
    "src/core/invite.js~invite#to",
    "class/src/core/Invite.js~Invite.html#instance-member-to",
    "src/core/Invite.js~Invite#to",
    "member"
  ],
  [
    "src/core/invite.js~invite#topic",
    "class/src/core/Invite.js~Invite.html#instance-member-topic",
    "src/core/Invite.js~Invite#topic",
    "member"
  ],
  [
    "src/core/invite.js~invite#uid",
    "class/src/core/Invite.js~Invite.html#instance-member-uid",
    "src/core/Invite.js~Invite#uid",
    "member"
  ],
  [
    "src/core/message.js",
    "file/src/core/Message.js.html",
    "src/core/Message.js",
    "file"
  ],
  [
    "src/core/message.js~message#edit",
    "class/src/core/Message.js~Message.html#instance-method-edit",
    "src/core/Message.js~Message#edit",
    "method"
  ],
  [
    "src/core/message.js~message#from",
    "class/src/core/Message.js~Message.html#instance-member-from",
    "src/core/Message.js~Message#from",
    "member"
  ],
  [
    "src/core/message.js~message#remove",
    "class/src/core/Message.js~Message.html#instance-method-remove",
    "src/core/Message.js~Message#remove",
    "method"
  ],
  [
    "src/core/message.js~message#roomid",
    "class/src/core/Message.js~Message.html#instance-member-roomId",
    "src/core/Message.js~Message#roomId",
    "member"
  ],
  [
    "src/core/message.js~message#text",
    "class/src/core/Message.js~Message.html#instance-member-text",
    "src/core/Message.js~Message#text",
    "member"
  ],
  [
    "src/core/message.js~message#uid",
    "class/src/core/Message.js~Message.html#instance-member-uid",
    "src/core/Message.js~Message#uid",
    "member"
  ],
  [
    "src/core/message.js~message.send",
    "class/src/core/Message.js~Message.html#static-method-send",
    "src/core/Message.js~Message.send",
    "method"
  ],
  [
    "src/core/participant.js",
    "file/src/core/Participant.js.html",
    "src/core/Participant.js",
    "file"
  ],
  [
    "src/core/participant.js~participant#role",
    "class/src/core/Participant.js~Participant.html#instance-member-role",
    "src/core/Participant.js~Participant#role",
    "member"
  ],
  [
    "src/core/participant.js~participant#status",
    "class/src/core/Participant.js~Participant.html#instance-member-status",
    "src/core/Participant.js~Participant#status",
    "member"
  ],
  [
    "src/core/participant.js~participant#uid",
    "class/src/core/Participant.js~Participant.html#instance-member-uid",
    "src/core/Participant.js~Participant#uid",
    "member"
  ],
  [
    "src/core/participant.js~participant#useragent",
    "class/src/core/Participant.js~Participant.html#instance-member-userAgent",
    "src/core/Participant.js~Participant#userAgent",
    "member"
  ],
  [
    "src/core/room.js",
    "file/src/core/Room.js.html",
    "src/core/Room.js",
    "file"
  ],
  [
    "src/core/room.js~room#close",
    "class/src/core/Room.js~Room.html#instance-method-close",
    "src/core/Room.js~Room#close",
    "method"
  ],
  [
    "src/core/room.js~room#extra",
    "class/src/core/Room.js~Room.html#instance-member-extra",
    "src/core/Room.js~Room#extra",
    "member"
  ],
  [
    "src/core/room.js~room#getlocalvideo",
    "class/src/core/Room.js~Room.html#instance-method-getLocalVideo",
    "src/core/Room.js~Room#getLocalVideo",
    "method"
  ],
  [
    "src/core/room.js~room#invite",
    "class/src/core/Room.js~Room.html#instance-method-invite",
    "src/core/Room.js~Room#invite",
    "method"
  ],
  [
    "src/core/room.js~room#join",
    "class/src/core/Room.js~Room.html#instance-method-join",
    "src/core/Room.js~Room#join",
    "method"
  ],
  [
    "src/core/room.js~room#leave",
    "class/src/core/Room.js~Room.html#instance-method-leave",
    "src/core/Room.js~Room#leave",
    "method"
  ],
  [
    "src/core/room.js~room#localstream",
    "class/src/core/Room.js~Room.html#instance-member-localStream",
    "src/core/Room.js~Room#localStream",
    "member"
  ],
  [
    "src/core/room.js~room#localstreams",
    "class/src/core/Room.js~Room.html#instance-method-localStreams",
    "src/core/Room.js~Room#localStreams",
    "method"
  ],
  [
    "src/core/room.js~room#messages",
    "class/src/core/Room.js~Room.html#instance-method-messages",
    "src/core/Room.js~Room#messages",
    "method"
  ],
  [
    "src/core/room.js~room#name",
    "class/src/core/Room.js~Room.html#instance-member-name",
    "src/core/Room.js~Room#name",
    "member"
  ],
  [
    "src/core/room.js~room#on",
    "class/src/core/Room.js~Room.html#instance-method-on",
    "src/core/Room.js~Room#on",
    "method"
  ],
  [
    "src/core/room.js~room#owner",
    "class/src/core/Room.js~Room.html#instance-member-owner",
    "src/core/Room.js~Room#owner",
    "member"
  ],
  [
    "src/core/room.js~room#participants",
    "class/src/core/Room.js~Room.html#instance-method-participants",
    "src/core/Room.js~Room#participants",
    "method"
  ],
  [
    "src/core/room.js~room#publish",
    "class/src/core/Room.js~Room.html#instance-method-publish",
    "src/core/Room.js~Room#publish",
    "method"
  ],
  [
    "src/core/room.js~room#remotestreams",
    "class/src/core/Room.js~Room.html#instance-method-remoteStreams",
    "src/core/Room.js~Room#remoteStreams",
    "method"
  ],
  [
    "src/core/room.js~room#sendmessage",
    "class/src/core/Room.js~Room.html#instance-method-sendMessage",
    "src/core/Room.js~Room#sendMessage",
    "method"
  ],
  [
    "src/core/room.js~room#share",
    "class/src/core/Room.js~Room.html#instance-method-share",
    "src/core/Room.js~Room#share",
    "method"
  ],
  [
    "src/core/room.js~room#status",
    "class/src/core/Room.js~Room.html#instance-member-status",
    "src/core/Room.js~Room#status",
    "member"
  ],
  [
    "src/core/room.js~room#uid",
    "class/src/core/Room.js~Room.html#instance-member-uid",
    "src/core/Room.js~Room#uid",
    "member"
  ],
  [
    "src/core/user.js",
    "file/src/core/User.js.html",
    "src/core/User.js",
    "file"
  ],
  [
    "src/core/user.js~user#anonymous",
    "class/src/core/User.js~User.html#instance-member-anonymous",
    "src/core/User.js~User#anonymous",
    "member"
  ],
  [
    "src/core/user.js~user#invite",
    "class/src/core/User.js~User.html#instance-method-invite",
    "src/core/User.js~User#invite",
    "method"
  ],
  [
    "src/core/user.js~user#lastseen",
    "class/src/core/User.js~User.html#instance-member-lastSeen",
    "src/core/User.js~User#lastSeen",
    "member"
  ],
  [
    "src/core/user.js~user#name",
    "class/src/core/User.js~User.html#instance-member-name",
    "src/core/User.js~User#name",
    "member"
  ],
  [
    "src/core/user.js~user#status",
    "class/src/core/User.js~User.html#instance-member-status",
    "src/core/User.js~User#status",
    "member"
  ],
  [
    "src/core/user.js~user#uid",
    "class/src/core/User.js~User.html#instance-member-uid",
    "src/core/User.js~User#uid",
    "member"
  ],
  [
    "src/core/stream/local.js",
    "file/src/core/stream/Local.js.html",
    "src/core/stream/Local.js",
    "file"
  ],
  [
    "src/core/stream/local.js~local#close",
    "class/src/core/stream/Local.js~Local.html#instance-method-close",
    "src/core/stream/Local.js~Local#close",
    "method"
  ],
  [
    "src/core/stream/local.js~local#constraints",
    "class/src/core/stream/Local.js~Local.html#instance-set-constraints",
    "src/core/stream/Local.js~Local#constraints",
    "member"
  ],
  [
    "src/core/stream/local.js~local#constraints",
    "class/src/core/stream/Local.js~Local.html#instance-get-constraints",
    "src/core/stream/Local.js~Local#constraints",
    "member"
  ],
  [
    "src/core/stream/local.js~local#container",
    "class/src/core/stream/Local.js~Local.html#instance-member-container",
    "src/core/stream/Local.js~Local#container",
    "member"
  ],
  [
    "src/core/stream/local.js~local#isvideoloaded",
    "class/src/core/stream/Local.js~Local.html#instance-member-isVideoLoaded",
    "src/core/stream/Local.js~Local#isVideoLoaded",
    "member"
  ],
  [
    "src/core/stream/local.js~local#media",
    "class/src/core/stream/Local.js~Local.html#instance-set-media",
    "src/core/stream/Local.js~Local#media",
    "member"
  ],
  [
    "src/core/stream/local.js~local#media",
    "class/src/core/stream/Local.js~Local.html#instance-get-media",
    "src/core/stream/Local.js~Local#media",
    "member"
  ],
  [
    "src/core/stream/local.js~local#mute",
    "class/src/core/stream/Local.js~Local.html#instance-method-mute",
    "src/core/stream/Local.js~Local#mute",
    "method"
  ],
  [
    "src/core/stream/local.js~local#muted",
    "class/src/core/stream/Local.js~Local.html#instance-member-muted",
    "src/core/stream/Local.js~Local#muted",
    "member"
  ],
  [
    "src/core/stream/local.js~local#node",
    "class/src/core/stream/Local.js~Local.html#instance-member-node",
    "src/core/stream/Local.js~Local#node",
    "member"
  ],
  [
    "src/core/stream/local.js~local#off",
    "class/src/core/stream/Local.js~Local.html#instance-method-off",
    "src/core/stream/Local.js~Local#off",
    "method"
  ],
  [
    "src/core/stream/local.js~local#on",
    "class/src/core/stream/Local.js~Local.html#instance-method-on",
    "src/core/stream/Local.js~Local#on",
    "method"
  ],
  [
    "src/core/stream/local.js~local#peerconnections",
    "class/src/core/stream/Local.js~Local.html#instance-member-peerConnections",
    "src/core/stream/Local.js~Local#peerConnections",
    "member"
  ],
  [
    "src/core/stream/local.js~local#roomid",
    "class/src/core/stream/Local.js~Local.html#instance-member-roomId",
    "src/core/stream/Local.js~Local#roomId",
    "member"
  ],
  [
    "src/core/stream/local.js~local#status",
    "class/src/core/stream/Local.js~Local.html#instance-member-status",
    "src/core/stream/Local.js~Local#status",
    "member"
  ],
  [
    "src/core/stream/local.js~local#switchcamera",
    "class/src/core/stream/Local.js~Local.html#instance-method-switchCamera",
    "src/core/stream/Local.js~Local#switchCamera",
    "method"
  ],
  [
    "src/core/stream/local.js~local#switchmicrophone",
    "class/src/core/stream/Local.js~Local.html#instance-method-switchMicrophone",
    "src/core/stream/Local.js~Local#switchMicrophone",
    "method"
  ],
  [
    "src/core/stream/local.js~local#type",
    "class/src/core/stream/Local.js~Local.html#instance-member-type",
    "src/core/stream/Local.js~Local#type",
    "member"
  ],
  [
    "src/core/stream/local.js~local#uid",
    "class/src/core/stream/Local.js~Local.html#instance-member-uid",
    "src/core/stream/Local.js~Local#uid",
    "member"
  ],
  [
    "src/core/stream/local.js~local#unmute",
    "class/src/core/stream/Local.js~Local.html#instance-method-unMute",
    "src/core/stream/Local.js~Local#unMute",
    "method"
  ],
  [
    "src/core/stream/local.js~local#updateconstraints",
    "class/src/core/stream/Local.js~Local.html#instance-method-updateConstraints",
    "src/core/stream/Local.js~Local#updateConstraints",
    "method"
  ],
  [
    "src/core/stream/remote.js",
    "file/src/core/stream/Remote.js.html",
    "src/core/stream/Remote.js",
    "file"
  ],
  [
    "src/core/stream/remote.js~remote#[key]",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-[key]",
    "src/core/stream/Remote.js~Remote#[key]",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#container",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-container",
    "src/core/stream/Remote.js~Remote#container",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#device",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-device",
    "src/core/stream/Remote.js~Remote#device",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#from",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-from",
    "src/core/stream/Remote.js~Remote#from",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#height",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-height",
    "src/core/stream/Remote.js~Remote#height",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#muted",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-muted",
    "src/core/stream/Remote.js~Remote#muted",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#node",
    "class/src/core/stream/Remote.js~Remote.html#instance-get-node",
    "src/core/stream/Remote.js~Remote#node",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#off",
    "class/src/core/stream/Remote.js~Remote.html#instance-method-off",
    "src/core/stream/Remote.js~Remote#off",
    "method"
  ],
  [
    "src/core/stream/remote.js~remote#on",
    "class/src/core/stream/Remote.js~Remote.html#instance-method-on",
    "src/core/stream/Remote.js~Remote#on",
    "method"
  ],
  [
    "src/core/stream/remote.js~remote#peerconnection",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-peerConnection",
    "src/core/stream/Remote.js~Remote#peerConnection",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#roomid",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-roomId",
    "src/core/stream/Remote.js~Remote#roomId",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#subscribe",
    "class/src/core/stream/Remote.js~Remote.html#instance-method-subscribe",
    "src/core/stream/Remote.js~Remote#subscribe",
    "method"
  ],
  [
    "src/core/stream/remote.js~remote#type",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-type",
    "src/core/stream/Remote.js~Remote#type",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#uid",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-uid",
    "src/core/stream/Remote.js~Remote#uid",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#unsubscribe",
    "class/src/core/stream/Remote.js~Remote.html#instance-method-unSubscribe",
    "src/core/stream/Remote.js~Remote#unSubscribe",
    "method"
  ],
  [
    "src/core/stream/remote.js~remote#useragent",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-userAgent",
    "src/core/stream/Remote.js~Remote#userAgent",
    "member"
  ],
  [
    "src/core/stream/remote.js~remote#width",
    "class/src/core/stream/Remote.js~Remote.html#instance-member-width",
    "src/core/stream/Remote.js~Remote#width",
    "member"
  ],
  [
    "src/core/stream/streammanager.js",
    "file/src/core/stream/StreamManager.js.html",
    "src/core/stream/StreamManager.js",
    "file"
  ],
  [
    "src/core/util/datasync.js",
    "file/src/core/util/DataSync.js.html",
    "src/core/util/DataSync.js",
    "file"
  ],
  [
    "src/core/util/log.js",
    "file/src/core/util/Log.js.html",
    "src/core/util/Log.js",
    "file"
  ],
  [
    "src/core/util/media.js",
    "file/src/core/util/Media.js.html",
    "src/core/util/Media.js",
    "file"
  ],
  [
    "src/core/util/media.js~media.attachstream",
    "class/src/core/util/Media.js~Media.html#static-method-attachStream",
    "src/core/util/Media.js~Media.attachStream",
    "method"
  ],
  [
    "src/core/util/media.js~media.constraints",
    "class/src/core/util/Media.js~Media.html#static-method-constraints",
    "src/core/util/Media.js~Media.constraints",
    "method"
  ],
  [
    "src/core/util/media.js~media.devices",
    "class/src/core/util/Media.js~Media.html#static-method-devices",
    "src/core/util/Media.js~Media.devices",
    "method"
  ],
  [
    "src/core/util/media.js~media.facingmode",
    "class/src/core/util/Media.js~Media.html#static-get-facingMode",
    "src/core/util/Media.js~Media.facingMode",
    "member"
  ],
  [
    "src/core/util/cache.js",
    "file/src/core/util/cache.js.html",
    "src/core/util/cache.js",
    "file"
  ],
  [
    "src/core/util/constants.js",
    "file/src/core/util/constants.js.html",
    "src/core/util/constants.js",
    "file"
  ],
  [
    "src/core/webrtc/peerconnection.js",
    "file/src/core/webrtc/PeerConnection.js.html",
    "src/core/webrtc/PeerConnection.js",
    "file"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#getmediabitratefromdesc",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-method-getMediaBitrateFromDesc",
    "src/core/webrtc/PeerConnection.js~PeerConnection#getMediaBitrateFromDesc",
    "method"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#isconnected",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-get-isConnected",
    "src/core/webrtc/PeerConnection.js~PeerConnection#isConnected",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#negotiated",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-member-negotiated",
    "src/core/webrtc/PeerConnection.js~PeerConnection#negotiated",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#pc",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-member-pc",
    "src/core/webrtc/PeerConnection.js~PeerConnection#pc",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#publish",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-member-publish",
    "src/core/webrtc/PeerConnection.js~PeerConnection#publish",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#remote",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-member-remote",
    "src/core/webrtc/PeerConnection.js~PeerConnection#remote",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#remotestream",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-get-remoteStream",
    "src/core/webrtc/PeerConnection.js~PeerConnection#remoteStream",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#setlowermediabitrates",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-method-setLowerMediaBitrates",
    "src/core/webrtc/PeerConnection.js~PeerConnection#setLowerMediaBitrates",
    "method"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#setmediabitrates",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-method-setMediaBitrates",
    "src/core/webrtc/PeerConnection.js~PeerConnection#setMediaBitrates",
    "method"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#socket",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-get-socket",
    "src/core/webrtc/PeerConnection.js~PeerConnection#socket",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#stackid",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-member-stackId",
    "src/core/webrtc/PeerConnection.js~PeerConnection#stackId",
    "member"
  ],
  [
    "src/core/webrtc/peerconnection.js~peerconnection#streamid",
    "class/src/core/webrtc/PeerConnection.js~PeerConnection.html#instance-member-streamId",
    "src/core/webrtc/PeerConnection.js~PeerConnection#streamId",
    "member"
  ],
  [
    "src/core/webrtc/peerconnectionmanager.js",
    "file/src/core/webrtc/PeerConnectionManager.js.html",
    "src/core/webrtc/PeerConnectionManager.js",
    "file"
  ],
  [
    "src/definitions/browser.js",
    "file/src/definitions/Browser.js.html",
    "src/definitions/Browser.js",
    "file"
  ],
  [
    "src/definitions/browser.js~browser",
    "typedef/index.html#static-typedef-Browser",
    "src/definitions/Browser.js~Browser",
    "typedef"
  ],
  [
    "src/definitions/codec.js",
    "file/src/definitions/Codec.js.html",
    "src/definitions/Codec.js",
    "file"
  ],
  [
    "src/definitions/codec.js~codec/audio",
    "typedef/index.html#static-typedef-Codec/audio",
    "src/definitions/Codec.js~Codec/audio",
    "typedef"
  ],
  [
    "src/definitions/codec.js~codec/video",
    "typedef/index.html#static-typedef-Codec/video",
    "src/definitions/Codec.js~Codec/video",
    "typedef"
  ],
  [
    "src/definitions/communicationquality.js",
    "file/src/definitions/CommunicationQuality.js.html",
    "src/definitions/CommunicationQuality.js",
    "file"
  ],
  [
    "src/definitions/communicationquality.js~communicationquality/bitrate",
    "typedef/index.html#static-typedef-CommunicationQuality/bitrate",
    "src/definitions/CommunicationQuality.js~CommunicationQuality/bitrate",
    "typedef"
  ],
  [
    "src/definitions/events.js",
    "file/src/definitions/Events.js.html",
    "src/definitions/Events.js",
    "file"
  ],
  [
    "src/definitions/events.js~events/invite",
    "typedef/index.html#static-typedef-Events/Invite",
    "src/definitions/Events.js~Events/Invite",
    "typedef"
  ],
  [
    "src/definitions/events.js~events/local",
    "typedef/index.html#static-typedef-Events/Local",
    "src/definitions/Events.js~Events/Local",
    "typedef"
  ],
  [
    "src/definitions/events.js~events/reach",
    "typedef/index.html#static-typedef-Events/Reach",
    "src/definitions/Events.js~Events/Reach",
    "typedef"
  ],
  [
    "src/definitions/events.js~events/room",
    "typedef/index.html#static-typedef-Events/Room",
    "src/definitions/Events.js~Events/Room",
    "typedef"
  ],
  [
    "src/definitions/events.js~events/stream",
    "typedef/index.html#static-typedef-Events/Stream",
    "src/definitions/Events.js~Events/Stream",
    "typedef"
  ],
  [
    "src/definitions/iceserver.js",
    "file/src/definitions/ICEServer.js.html",
    "src/definitions/ICEServer.js",
    "file"
  ],
  [
    "src/definitions/iceserver.js~iceserver",
    "typedef/index.html#static-typedef-ICEServer",
    "src/definitions/ICEServer.js~ICEServer",
    "typedef"
  ],
  [
    "src/definitions/streamtypes.js",
    "file/src/definitions/StreamTypes.js.html",
    "src/definitions/StreamTypes.js",
    "file"
  ],
  [
    "src/definitions/streamtypes.js~streamtypes",
    "typedef/index.html#static-typedef-StreamTypes",
    "src/definitions/StreamTypes.js~StreamTypes",
    "typedef"
  ],
  [
    "src/external/datasync/webcom.js",
    "file/src/external/datasync/Webcom.js.html",
    "src/external/datasync/Webcom.js",
    "file"
  ],
  [
    "src/external/datasync/webcom.js~webcom",
    "https://datasync.orange.com/doc/Webcom.html",
    "src/external/datasync/Webcom.js~Webcom",
    "external"
  ],
  [
    "src/external/datasync/api.datasnapshot.js",
    "file/src/external/datasync/api.DataSnapshot.js.html",
    "src/external/datasync/api.DataSnapshot.js",
    "file"
  ],
  [
    "src/external/datasync/api.ondisconnect.js",
    "file/src/external/datasync/api.OnDisconnect.js.html",
    "src/external/datasync/api.OnDisconnect.js",
    "file"
  ],
  [
    "src/external/datasync/api.query.js",
    "file/src/external/datasync/api.Query.js.html",
    "src/external/datasync/api.Query.js",
    "file"
  ],
  [
    "src/external/datasync/api.query.js~webcom/api.query~cancelcallback",
    "https://datasync.orange.com/doc/api.Query.html#~cancelCallback",
    "src/external/datasync/api.Query.js~Webcom/api.Query~cancelCallback",
    "external"
  ],
  [
    "src/external/dom/element.js",
    "file/src/external/dom/Element.js.html",
    "src/external/dom/Element.js",
    "file"
  ],
  [
    "src/external/dom/element.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "src/external/dom/Element.js~Element",
    "external"
  ],
  [
    "src/external/webrtc/mediadeviceinfo.js",
    "file/src/external/webrtc/MediaDeviceInfo.js.html",
    "src/external/webrtc/MediaDeviceInfo.js",
    "file"
  ],
  [
    "src/external/webrtc/mediadeviceinfo.js~mediadeviceinfo",
    "http://w3c.github.io/mediacapture-main/#idl-def-MediaDeviceInfo",
    "src/external/webrtc/MediaDeviceInfo.js~MediaDeviceInfo",
    "external"
  ],
  [
    "src/external/webrtc/mediastream.js",
    "file/src/external/webrtc/MediaStream.js.html",
    "src/external/webrtc/MediaStream.js",
    "file"
  ],
  [
    "src/external/webrtc/mediastream.js~mediastream",
    "https://w3c.github.io/mediacapture-main/getusermedia.html#stream-api",
    "src/external/webrtc/MediaStream.js~MediaStream",
    "external"
  ],
  [
    "src/external/webrtc/mediastreamconstrains.js",
    "file/src/external/webrtc/MediaStreamConstrains.js.html",
    "src/external/webrtc/MediaStreamConstrains.js",
    "file"
  ],
  [
    "src/external/webrtc/mediastreamconstrains.js~mediastreamconstraints",
    "https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaStreamConstraints",
    "src/external/webrtc/MediaStreamConstrains.js~MediaStreamConstraints",
    "external"
  ],
  [
    "src/external/webrtc/mediatrackconstraints.js",
    "file/src/external/webrtc/MediaTrackConstraints.js.html",
    "src/external/webrtc/MediaTrackConstraints.js",
    "file"
  ],
  [
    "src/external/webrtc/mediatrackconstraints.js~mediatrackconstraints",
    "https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaTrackConstraints",
    "src/external/webrtc/MediaTrackConstraints.js~MediaTrackConstraints",
    "external"
  ],
  [
    "src/external/webrtc/rtcpeerconnection.js",
    "file/src/external/webrtc/RTCPeerConnection.js.html",
    "src/external/webrtc/RTCPeerConnection.js",
    "file"
  ],
  [
    "src/external/webrtc/rtcpeerconnection.js~rtcpeerconnection",
    "https://w3c.github.io/webrtc-pc/#interface-definition",
    "src/external/webrtc/RTCPeerConnection.js~RTCPeerConnection",
    "external"
  ],
  [
    "src/external/webrtc/rtcrtpsender.js",
    "file/src/external/webrtc/RTCRtpSender.js.html",
    "src/external/webrtc/RTCRtpSender.js",
    "file"
  ],
  [
    "src/external/webrtc/rtcrtpsender.js~rtcrtpsender",
    "https://w3c.github.io/webrtc-pc/#rtcrtpsender-interface",
    "src/external/webrtc/RTCRtpSender.js~RTCRtpSender",
    "external"
  ],
  [
    "src/external/webrtc/rtcsessiondescription.js",
    "file/src/external/webrtc/RTCSessionDescription.js.html",
    "src/external/webrtc/RTCSessionDescription.js",
    "file"
  ],
  [
    "src/external/webrtc/rtcsessiondescription.js~rtcsessiondescription",
    "https://w3c.github.io/webrtc-pc/#rtcsessiondescription-class",
    "src/external/webrtc/RTCSessionDescription.js~RTCSessionDescription",
    "external"
  ]
]